# wrangler.toml
# Cloudflare Worker configuration for Guard Duty Management System

name = "smart-guard-duty-system-api"
main = "worker/index.js"
compatibility_date = "2024-04-01"

[vars]
# Add any environment variables here if needed
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB" # Name used to access D1 in the worker code (env.DB)
database_name = "sgds"
database_id = "40657dd7-daf7-44b3-a737-f5b4c22aecb1"
migrations_dir = "migrations"
