# .github/workflows/deploy.yml
name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Workspace Dependencies
        run: npm install

      - name: Build React Client
        env:
          VITE_API_URL: "https://sgds-backend.onrender.com" # Replace with your actual Render API URL after deploying
        run: npm run build --workspace=client

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist
          branch: gh-pages
